# Theme variables
theme: jekyll-theme-minimal
title: Zettamachine - Digital Thinking
description: Zettamachine is a blog on Architecture and Digital Transformation
author: Mehmet Akyuz

#Navigation Variables
url: 'https://zettamachine.com'
permalink: /:year/:month/:day/:title:output_ext
paginate: 4

#Tags
disqus: zettamachine

#Content
excerpt_separator: <!--more-->