# Theme variables
theme: jekyll-theme-minimal
title: Zettamachine - Digital Thinking
description: Zettamachine is a blog on Architecture and Digital Transformation

#Navigation Variables
url: 'https://zettamachine.com'
permalink: /:year/:month/:day/:title:output_ext
paginate: 4

#Tags
google_analytics: UA-43111163-1
disqus: zettamachine

#Formatting
excerpt_separator: <!--more-->