# Theme variables
theme: jekyll-theme-minimal
title: zettamachine - Digital Thinking, Digital Architecture
description: Zettamachine is a blog on Enterprise Architecture, Digital Transformation and Design Thinking. 
author: Mehmet Akyuz

#Navigation Variables
url: 'https://zettamachine.com'
permalink: /:year/:month/:day/:title:output_ext
paginate: 3

#Tags
disqus: zettamachine

#Content
excerpt_separator: <!--more-->