# Theme variables
remote_theme: zettamachine-theme
title: zettamachine - Digital Thinking, Digital Architecture
description: Zettamachine is a blog on Enterprise Architecture, Digital Transformation and Design Thinking. 
author: Mehmet Akyuz
logo: /images/zettamachine.logo.digitalthinking.png

#Navigation variables
url: 'https://zettamachine.com'
permalink: /:year/:month/:day/:title:output_ext

#Tags & social
disqus: zettamachine
twitter:
  username: _makyuz
  card: summary
social:
  name: Mehmet Akyuz
  links:
    - https://twitter.com/_makyuz
    - https://www.linkedin.com/in/makyuz
    - https://github.com/makiato

#Content
excerpt_separator: <!--more-->

#Plugins
plugins: 
  - jekyll-seo-tag
